package com.liyang.user.mapper;

import com.liyang.user.entity.Stu;
import com.liyang.user.entity.StuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int countByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int deleteByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int insert(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int insertSelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    List<Stu> selectByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    Stu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Stu record, @Param("example") StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int updateByExample(@Param("record") Stu record, @Param("example") StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int updateByPrimaryKeySelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.STU
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    int updateByPrimaryKey(Stu record);
}