package com.liyang.book.entity;

import com.liyang.category.entity.Category;
import com.liyang.gys.entity.Gys;

import java.util.Date;
import java.util.List;

public class Book {
    private List<Bookpic> bps;
    private Category ca;
    private Gys gys;

    public List<Bookpic> getBps() {
        return bps;
    }

    public void setBps(List<Bookpic> bps) {
        this.bps = bps;
    }

    public Category getCa() {
        return ca;
    }

    public void setCa(Category ca) {
        this.ca = ca;
    }

    public Gys getGys() {
        return gys;
    }

    public void setGys(Gys gys) {
        this.gys = gys;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.ID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.NAME
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PRICE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private Integer price;
     private String pdate;

    public String getPdate() {
        return pdate;
    }

    public void setPdate(String pdate) {
        this.pdate = pdate;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.STATUS
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.DEL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private Short del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private String categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.GYSID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private String gysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.SL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    private Short sl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.ID
     *
     * @return the value of SCOTT.BOOK.ID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.ID
     *
     * @param id the value for SCOTT.BOOK.ID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.NAME
     *
     * @return the value of SCOTT.BOOK.NAME
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.NAME
     *
     * @param name the value for SCOTT.BOOK.NAME
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @return the value of SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @param author the value for SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PRICE
     *
     * @return the value of SCOTT.BOOK.PRICE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PRICE
     *
     * @param price the value for SCOTT.BOOK.PRICE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @return the value of SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @param publishdate the value for SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.STATUS
     *
     * @return the value of SCOTT.BOOK.STATUS
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.STATUS
     *
     * @param status the value for SCOTT.BOOK.STATUS
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.DEL
     *
     * @return the value of SCOTT.BOOK.DEL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.DEL
     *
     * @param del the value for SCOTT.BOOK.DEL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @return the value of SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @param categoryid the value for SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.GYSID
     *
     * @return the value of SCOTT.BOOK.GYSID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public String getGysid() {
        return gysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.GYSID
     *
     * @param gysid the value for SCOTT.BOOK.GYSID
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setGysid(String gysid) {
        this.gysid = gysid == null ? null : gysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.SL
     *
     * @return the value of SCOTT.BOOK.SL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public Short getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.SL
     *
     * @param sl the value for SCOTT.BOOK.SL
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    public void setSl(Short sl) {
        this.sl = sl;
    }
}