package com.liyang.category.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.CATEGORY.ID
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.CATEGORY.NAME
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.CATEGORY.ID
     *
     * @return the value of SCOTT.CATEGORY.ID
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.CATEGORY.ID
     *
     * @param id the value for SCOTT.CATEGORY.ID
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.CATEGORY.NAME
     *
     * @return the value of SCOTT.CATEGORY.NAME
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.CATEGORY.NAME
     *
     * @param name the value for SCOTT.CATEGORY.NAME
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}