package com.liyang.gys.mapper;

import com.liyang.gys.entity.Gys;
import com.liyang.gys.entity.GysExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int countByExample(GysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int deleteByExample(GysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int insert(Gys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int insertSelective(Gys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    List<Gys> selectByExample(GysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    Gys selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") Gys record, @Param("example") GysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int updateByExample(@Param("record") Gys record, @Param("example") GysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int updateByPrimaryKeySelective(Gys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.GYS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    int updateByPrimaryKey(Gys record);

    List<Gys> querySome(Map<String,Object> map);

    int queryCount(Map<String, Object> map);
}