package com.liyang.gys.entity;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.CITY.ID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.CITY.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.CITY.PID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.CITY.ID
     *
     * @return the value of SCOTT.CITY.ID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.CITY.ID
     *
     * @param id the value for SCOTT.CITY.ID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.CITY.NAME
     *
     * @return the value of SCOTT.CITY.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.CITY.NAME
     *
     * @param name the value for SCOTT.CITY.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.CITY.PID
     *
     * @return the value of SCOTT.CITY.PID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.CITY.PID
     *
     * @param pid the value for SCOTT.CITY.PID
     *
     * @mbggenerated Mon Jul 29 09:27:21 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}