package com.liyang.gys.entity;

public class Gys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.GYS.ID
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.GYS.NAME
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.GYS.LXR
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.GYS.PHONE
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.GYS.ADDRESS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.GYS.ID
     *
     * @return the value of SCOTT.GYS.ID
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.GYS.ID
     *
     * @param id the value for SCOTT.GYS.ID
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.GYS.NAME
     *
     * @return the value of SCOTT.GYS.NAME
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.GYS.NAME
     *
     * @param name the value for SCOTT.GYS.NAME
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.GYS.LXR
     *
     * @return the value of SCOTT.GYS.LXR
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.GYS.LXR
     *
     * @param lxr the value for SCOTT.GYS.LXR
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.GYS.PHONE
     *
     * @return the value of SCOTT.GYS.PHONE
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.GYS.PHONE
     *
     * @param phone the value for SCOTT.GYS.PHONE
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.GYS.ADDRESS
     *
     * @return the value of SCOTT.GYS.ADDRESS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.GYS.ADDRESS
     *
     * @param address the value for SCOTT.GYS.ADDRESS
     *
     * @mbggenerated Sun Jul 28 17:38:28 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}