package com.liyang.gys.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.PROVINCE.ID
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.PROVINCE.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.PROVINCE.ID
     *
     * @return the value of SCOTT.PROVINCE.ID
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.PROVINCE.ID
     *
     * @param id the value for SCOTT.PROVINCE.ID
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.PROVINCE.NAME
     *
     * @return the value of SCOTT.PROVINCE.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.PROVINCE.NAME
     *
     * @param name the value for SCOTT.PROVINCE.NAME
     *
     * @mbggenerated Mon Jul 29 09:27:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}