package com.liyang.book.mapper;

import com.liyang.book.entity.Bookpic;
import com.liyang.book.entity.BookpicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookpicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int countByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int deleteByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int insert(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int insertSelective(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    List<Bookpic> selectByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    Bookpic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bookpic record, @Param("example") BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int updateByExample(@Param("record") Bookpic record, @Param("example") BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int updateByPrimaryKeySelective(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Sun Jul 28 17:37:35 CST 2019
     */
    int updateByPrimaryKey(Bookpic record);

    void setPicNotAsFM();

    void setPicAsFM(@Param("bpid") String bpid);
}