package com.liyang.category.mapper;

import com.liyang.category.entity.Category;
import com.liyang.category.entity.CategoryExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    Category selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Sun Jul 28 17:36:54 CST 2019
     */
    int updateByPrimaryKey(Category record);

    List<Category> querySome(Map<String, Object> map);
}