package com.liyang.user.entity;

public class Stu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STU.id
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STU.name
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.STU.pwd
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STU.id
     *
     * @return the value of SCOTT.STU.id
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STU.id
     *
     * @param id the value for SCOTT.STU.id
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STU.name
     *
     * @return the value of SCOTT.STU.name
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STU.name
     *
     * @param name the value for SCOTT.STU.name
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.STU.pwd
     *
     * @return the value of SCOTT.STU.pwd
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.STU.pwd
     *
     * @param pwd the value for SCOTT.STU.pwd
     *
     * @mbggenerated Mon Jul 29 10:21:15 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}